### ISSUE TITLE
TS3 Dream Launcher Closes

### ISSUE THREAD

**Issue by SkyWoofs** [marcos4503/ts3-dream-launcher#4]
When I click play for The Sims 3 on steam, the dream launcher opens. At the bottom it tells me it is working on 15 tasks, when it gets down to 1 task, the launcher closes and never reopens again unless I hit play on steam. It is a repeating cycle of the same thing.
![image_2024-07-27_121522976](https://github.com/user-attachments/assets/4d428fba-6335-4a7b-b9d0-b62275dab072)

**Comment by marcos4503** [comment]
Hi! Is your Sims 3 installation new?

Also, what is the name of the Sims 3 folder in Documents on your computer?

Finally, have you successfully launched the game at least once?

**Comment by SkyWoofs** [comment]
1. Yes, I redid all installation, including dream launcher to be sure but I end up with the same issue
2. Documents > Electronic Arts > The Sims 3, is this what you mean? It is just called The Sims 3
3. Yes I have

**Comment by marcos4503** [comment]
I forgot to ask. Have you ever installed any mods, patches or anything else through the Launcher?

So I can try to reproduce the problem, could you zip your The Sims 3 folder of your Documents and post it here?

**Comment by SkyWoofs** [comment]
I've installed Alder Laker Patch and the Language Patch.

It says my file is too big to upload

![image_2024-07-27_131605686](https://github.com/user-attachments/assets/9b550d1c-1268-440d-af67-32b911ed1923)

**Comment by marcos4503** [comment]
Got it. Could you upload this compressed file to a cloud and post the link here?

This would be very necessary because with the files, it would be easier for me to try to reproduce the problem.

**Comment by SkyWoofs** [comment]
https://drive.google.com/file/d/1AigLRe71-20YVA8WBqGO82cjY85bG0Nx/view?usp=sharing

Let me know if that doesn't work, and thank you for helping! (:

**Comment by marcos4503** [comment]
Sorry for the delay, I had some issues to resolve, but I have already analyzed the folder you sent.

Unfortunately I was unable to reproduce the problem... :/

So that I can expand the test scenario, would it be possible for you to share your "Bin" folder? It can be found in the following directory...

<install_dir>\Game
Example...
I:\SteamLibrary\steamapps\common\The Sims 3\Game

The folder you send must have been edited only by Dream Launcher, to ensure the scenario is as close as possible to your scenario.
