### ISSUE TITLE
The Sims 3 folder cannot be found in documents.

### ISSUE THREAD

**Issue by Mid54999** [marcos4503/ts3-dream-launcher#5]
Hello,

Recently I had uninstalled OneDrive off of my computer.  Knowing that it would change the path to my documents, I uninstalled the game and launcher and reinstalled fresh once OneDrive was completely uninstalled.  Since then, the launcher is not recognizing the sims 3 folder in my documents. It says, "The Sims 3 folder could not be found in documents. Run the game and restart Dream Launcher so that all functions are accessible."  I have run the game many times since and there is definitely a Sims 3 folder in the following path: C:\Users\<user>\Documents\Electronic Arts\The Sims 3.  Interestingly, the launcher will still start the game at my last save, but I have no other functions available within the launcher.  What can I do to fix this?  

Thanks so much for your help!

**Comment by marcos4503** [comment]
Hi!

Dream Launcher uses the path provided by Windows, to what it considers to be the "Documents" folder. If Dream Launcher is not recognizing your game folder, it may be that Windows is reporting the old OneDrive "Documents" path.

To test this, try placing your "The Sims 3" folder in the old OneDrive path, which should be something like "C:\Users\<user>\OneDrive\Documents". If Dream Launcher recognizes the folder, it means that Windows is still using the old path.

Even after uninstalling OneDrive, the OneDrive "Documents" path may still be used. In many cases, before uninstalling OneDrive, it is necessary to "unregister" the folders it replaces, so that Windows returns to using the default paths for Documents, Pictures, Desktop, etc.

**Comment by Mid54999** [comment]
Marcos, thank you so much for your help!  You were right, the remaining traces of OneDrive were the issue.  Once I made edits to the registry keys still pointing to OneDrive, the launcher opened just fine.  Thanks again!

**Comment by marcos4503** [comment]
I'm glad it worked! :)
